### ISSUE TITLE
'citingArticles was not recognized' error from WoS Web Services Lite v3.0

### ISSUE THREAD

**Issue by MrkGrgsn** [QUTlib/citation-import#2]
> [quteprints wos] Warning: Unable to retrieve citation data for EPrint ID 377 from Web of Science: Message part {http://woksearchlite.v3.wokmws.thomsonreuters.com}citingArticles was not recognized. (Does it exist in service WSDL?)
> [quteprints wos] Warning: No match for EPrint ID 377.

**Comment by phluid61** [comment]
No longer required?
