### ISSUE TITLE
Minor fixes for Scopus queries

### ISSUE THREAD

**Issue by mpbraendle** [QUTlib/citation-import#24]
DOIs with brackets can be handled, if they are enclosed within double quotes:
Line 299: return 'doi("' . $eprint->get_value( 'id_number' ) . '")';
Line 450: return 1;

Author names may make problems if they contain brackets. Enclosing in double quotes fixes this:
Line 332: my $authlastname = '"' . $authors[ 0 ]->{family} . '"';

**Comment by phluid61** [comment]
I think I should perhaps craft a proper heavyweight quoting function for each possible parameter.

**Comment by phluid61** [comment]
I forgot to put a pointer to this issue in the commit message for 3a71c44.
